### ISSUE TITLE
Peer-to-peer code review 19-11-2021

### ISSUE THREAD

**Issue by ghost** [codepantherr/capstone-project-js#30]
## HIGHLIGHTS 
- Functions for counting likes is behaving as expected 
- The design is outstanding 
- Your documentation management is top class
## SUGGESTIONS
- It would be great to move your linters config files into gitignore file to keep the repo clean.

Other than that You are doing a great job, keep it up Cheers! :sunglasses: :v:

**Comment by Cathella** [comment]
## Hi @codepantherr 👋🏻 
You have done great so far working on your capstone project.

## Highlights 👏🏻 
✔️ Well refactored functions
✔️ Well thought-of design to display items from the Api

**Comment by codepantha** [comment]
@Cathella Thank you for your kind words. 
@Hope1226 Thank you for the kind words. I will implement your observation.
